### ISSUE TITLE
Can't attached to Java 11.0.2, JavaFX 11.0.2 project launched from IntelliJ 2018.3.4

### ISSUE THREAD

**Issue by jschlade** [JonathanGiles/scenic-view#45]
Does Scene View 11.0.1 work in this configuration? Was curious what this application would offer.

Thanks

**Comment by jperedadnr** [comment]
It should work. However there is a known issue if you run your project with Maven `exec:java`. 
If that is the case, you can change it and use `exec:exec`, see [this](https://github.com/openjfx/openjfx-docs/issues/76).

**Comment by jschlade** [comment]
Got it to work on my home laptop... might be an issue with virus protection software on my work one. Still trying to determine how useful this is to me.

Thanks
