### ISSUE TITLE
Inaccessible download URL 

### ISSUE THREAD

**Issue by peterzen** [JonathanGiles/scenic-view#48]
The download URL (https://jogilesoss.blob.core.windows.net/scenic-view/scenicview-linux.zip) does not currently resolve:

```
$ host jogilesoss.blob.core.windows.net 1.1.1.1
Using domain server:
Name: 1.1.1.1
Address: 1.1.1.1#53
Aliases: 

Host jogilesoss.blob.core.windows.net not found: 3(NXDOMAIN)
```

**Comment by jperedadnr** [comment]
Thanks for pointing this out. There was a typo in the release links that has been fixed now.
