### ISSUE TITLE
can not open the jar file

### ISSUE THREAD

**Issue by aliShreef** [JonathanGiles/scenic-view#57]
I am trying to run the jar file from lib folder , but nothing happen.

also i tried to run it from CMD but i got this message :

![image](https://user-images.githubusercontent.com/20012415/74832543-9a417600-5328-11ea-8315-fd803dc8739e.png)

and this is my JAVA_HOME & JRE_HOME variable.

![image](https://user-images.githubusercontent.com/20012415/74832672-e1c80200-5328-11ea-92d6-c26efbaacd41.png)

thank you.

**Comment by Oliver-Loeffler** [comment]
I have now played with JDK-8 and JDK-11 versions.

```cmd
git clone --branch jdk-8 https://github.com/JonathanGiles/scenic-view.git
cd scenic-view
gradle assemble run
```

For the current JDK-11 compatible version, this worked:
```
git clone https://github.com/JonathanGiles/scenic-view.git
cd scenic-view
gradlew build run
```

When starting manually, ensure that the JavaFX runtime is available (https://openjfx.io)
One can download the runtime here: https://gluonhq.com/products/javafx/

```cmd
set PATH_TO_FX="path\to\javafx-sdk-11\lib"
```

Then continue building and running the Scenic-View. Scenic-View requires different JavaFX modules. Manually launching Java requires to provide the individual modules. The module `javafx.base` must not be provided manually, as it is a transitive depenedency of the other modules.

```
git clone https://github.com/JonathanGiles/scenic-view.git
cd scenic-view
gradlew build
cd build\libs
java --module-path %PATH_TO_FX% --add-modules javafx.controls,javafx.graphics,javafx.fxml,javafx.web -jar scenicview.jar
```

**Comment by Oliver-Loeffler** [comment]
According to `build.gradle`, the JavaFX Swing module is needed as well. This will be relevant, when the `JFXPanel` is used in the project to be analysed. In this case, the java command shall look as follows:

```PowerShell
java --module-path $env:PATH_TO_FX --add-modules javafx.controls,javafx.graphics,javafx.fxml,javafx.web,javafx.swing -jar .\scenicview.jar
```

**Comment by aliShreef** [comment]
@Oliver-Loeffler  , thank you so much for your valuable replay to my point.
actually i am able to run the jar now from power shell with this command : 

`java --module-path $env:PATH_TO_FX --add-modules javafx.controls,javafx.graphics,javafx.fxml,javafx.web,javafx.swing -jar .\scenicview.jar`

, but nothing display. look : 

![image](https://user-images.githubusercontent.com/20012415/75133280-35509c00-56eb-11ea-8693-e32691bf6b9d.png)

also, when i follow your way for JDK 11 , i got this error when run this command : 

`gradlew build run `

![image](https://user-images.githubusercontent.com/20012415/75133380-9b3d2380-56eb-11ea-93c5-60853dc1b975.png)

 note that , i set PATH_TO_FX as it is as variable name , and set the value of the variable to my local javaFX SDK lib directory

**Comment by aliShreef** [comment]
should i start my application along with scenic-view in order to load the hierarchy of view ?

**Comment by Oliver-Loeffler** [comment]
In PowerShell instead of `gradlew build run` you must type `./gradlew build run`. 
Yes, you have to run your application along with Scenic-View. Scenic-View permanently scans for JavaFX applications around.

The ThreeDom will only work, when started as a project dependency.
Well, I haven't this tried yet with JDK-11 version.
```
Button button = new Button("Hello");
VBox vbox = new VBox(button);  
Scene scene = new Scene(vbox);
primaryStage.setScene(scene);
primaryStage.show();

// only works, if Scenic-View has been added as a dependency to your project
ScenicView.show(scene);
```

**Comment by aliShreef** [comment]
i do not know what i say actually , you save my all life. 

currently i am able to run the jar from power shell correctly , but i still can not run it by just double click. when i double click jars , nothings is happen and when i run from power shell like this 

![image](https://user-images.githubusercontent.com/20012415/75153814-592cd580-571d-11ea-9f6a-924667b9430f.png)

i got 

`classNotFoundException    `

what is the issue or i am missing  if i am able to run it from power shell but not from just clicking on it ?

**Comment by Oliver-Loeffler** [comment]
Double clicking the JAR is equivalent to the attempt of running the jar with `javaw -jar scenicview.jar`. In this case, all the required modules will not be loaded.

Instead, you could write a BATCH or CMD file which is then executed, it could look like:

*start-scenic-view.cmd*
```
@echo off
javaw --module-path %PATH_TO_FX% --add-modules javafx.controls,javafx.graphics,javafx.fxml,javafx.web -jar %LOCATION_OF_JAR%\scenicview.jar
```

 * `%LOCATION_OF_JAR%` directory where your JAR is located
* `%PATH_TO_FX%` is your path\to\javafx-sdk-11\lib

This batch file will be runnable via double click.

**Comment by aliShreef** [comment]
Thank you so much for your support @Oliver-Loeffler  , you help me a lot.
i appreciate it .
